export const contactJson = [
  {
    id: '1',
    name: 'Afrin Sabila',
    status: 'Life is beautiful 👌',
    phone: '+91 98765 43210',
    profileImage: 'https://randomuser.me/api/portraits/women/11.jpg',
  },
  {
    id: '2',
    name: 'Adil Adnan',
    status: 'Be your own hero 💪',
    phone: '+91 98765 43211',
    profileImage: 'https://randomuser.me/api/portraits/men/12.jpg',
  },
  {
    id: '3',
    name: 'Alex Linderson',
    status: 'Stay positive ✨',
    phone: '+91 98765 43212',
    profileImage: 'https://randomuser.me/api/portraits/men/13.jpg',
  },
  {
    id: '4',
    name: 'Bristy Haque',
    status: 'Keep working ✍️',
    phone: '+91 98765 43213',
    profileImage: 'https://randomuser.me/api/portraits/women/14.jpg',
  },
  {
    id: '5',
    name: 'John Borino',
    status: 'Make yourself proud 😍',
    phone: '+91 98765 43214',
    profileImage: 'https://randomuser.me/api/portraits/men/15.jpg',
  },
  {
    id: '6',
    name: 'Borsha Akther',
    status: 'Flowers are beautiful 🌸',
    phone: '+91 98765 43215',
    profileImage: 'https://randomuser.me/api/portraits/women/16.jpg',
  },
  {
    id: '7',
    name: 'Chris Evans',
    status: 'Dream big 🚀',
    phone: '+91 98765 43216',
    profileImage: 'https://randomuser.me/api/portraits/men/17.jpg',
  },
  {
    id: '8',
    name: 'Charlotte King',
    status: 'Be kind 💖',
    phone: '+91 98765 43217',
    profileImage: 'https://randomuser.me/api/portraits/women/18.jpg',
  },
  {
    id: '9',
    name: 'David Miller',
    status: 'Work smart ⚡',
    phone: '+91 98765 43218',
    profileImage: 'https://randomuser.me/api/portraits/men/19.jpg',
  },
  {
    id: '10',
    name: 'Daisy Johnson',
    status: 'Enjoy little things 🌈',
    phone: '+91 98765 43219',
    profileImage: 'https://randomuser.me/api/portraits/women/20.jpg',
  },
  {
    id: '11',
    name: 'Emma Watson',
    status: 'Stay classy 🌷',
    phone: '+91 98765 43220',
    profileImage: 'https://randomuser.me/api/portraits/women/21.jpg',
  },
  {
    id: '12',
    name: 'Fahim Rahman',
    status: 'Never give up 🔥',
    phone: '+91 98765 43221',
    profileImage: 'https://randomuser.me/api/portraits/men/22.jpg',
  },
  {
    id: '13',
    name: 'Grace Hall',
    status: 'Smile more 😊',
    phone: '+91 98765 43222',
    profileImage: 'https://randomuser.me/api/portraits/women/23.jpg',
  },
  {
    id: '14',
    name: 'Henry Wilson',
    status: 'Stay focused 🎯',
    phone: '+91 98765 43223',
    profileImage: 'https://randomuser.me/api/portraits/men/24.jpg',
  },
  {
    id: '15',
    name: 'Isabella Moore',
    status: 'Love yourself 💕',
    phone: '+91 98765 43224',
    profileImage: 'https://randomuser.me/api/portraits/women/25.jpg',
  },
  {
    id: '16',
    name: 'James Anderson',
    status: 'Hustle hard 💼',
    phone: '+91 98765 43225',
    profileImage: 'https://randomuser.me/api/portraits/men/26.jpg',
  },
  {
    id: '17',
    name: 'Lily Adams',
    status: 'Choose happiness 🌻',
    phone: '+91 98765 43226',
    profileImage: 'https://randomuser.me/api/portraits/women/27.jpg',
  },
  {
    id: '18',
    name: 'Michael Scott',
    status: 'No limits 🚀',
    phone: '+91 98765 43227',
    profileImage: 'https://randomuser.me/api/portraits/men/28.jpg',
  },
  {
    id: '19',
    name: 'Noah Taylor',
    status: 'One day at a time ⏳',
    phone: '+91 98765 43228',
    profileImage: 'https://randomuser.me/api/portraits/men/29.jpg',
  },
  {
    id: '20',
    name: 'Olivia Brown',
    status: 'Positive vibes ✨',
    phone: '+91 98765 43229',
    profileImage: 'https://randomuser.me/api/portraits/women/30.jpg',
  },
  {
    id: '21',
    name: 'Ryan Cooper',
    status: 'Stay strong 💪',
    phone: '+91 98765 43230',
    profileImage: 'https://randomuser.me/api/portraits/men/31.jpg',
  },
  {
    id: '22',
    name: 'Sophia Lee',
    status: 'Create magic ✨',
    phone: '+91 98765 43231',
    profileImage: 'https://randomuser.me/api/portraits/women/32.jpg',
  },
  {
    id: '23',
    name: 'Sheik Sadi',
    status: 'Knowledge is power 📚',
    phone: '+91 98765 43232',
    profileImage: 'https://randomuser.me/api/portraits/men/33.jpg',
  },
  {
    id: '24',
    name: 'William Turner',
    status: 'Live free 🌍',
    phone: '+91 98765 43233',
    profileImage: 'https://randomuser.me/api/portraits/men/34.jpg',
  },
  {
    id: '25',
    name: 'Zara Khan',
    status: 'Believe in yourself 🌟',
    phone: '+91 98765 43234',
    profileImage: 'https://randomuser.me/api/portraits/women/35.jpg',
  },
];
